### ISSUE TITLE
weibo数据集

### ISSUE THREAD

**Issue by goingcoder** [CPF-NLPR/AT4ChineseNER#10]
weibo 数据集中有两类实体，NAM和NOM，在您预处理的时候，NOM去掉了。也就是只关注了NAM部分。您论文的实验结果是基于这两种类别是同时训练的还是分开训练的呢？谢谢

**Comment by CPF-NLPR** [comment]
Overall结果需要同时考虑NAM和NOM，NAM结果只需考虑NAM，过滤掉NOM，NOM结果只需考虑NOM，过滤掉NAM
