### ISSUE TITLE
weibo数据达不到论文效果

### ISSUE THREAD

**Issue by goingcoder** [CPF-NLPR/AT4ChineseNER#11]
我使用这个代码发现在测试集上最好的F1：51.51,达不到53.08。

**Comment by CPF-NLPR** [comment]
在ckpt这个文件夹下有预训练的模型，可以直接运行得到实验结果。如果自己训练测试，weibo数据集比较小，过拟合问题比较严重，受参数初始化的影响，结果有可能会有一些波动，你可以多次实验看一下结果或者调整一下个别参数。

**Comment by goingcoder** [comment]
> 在ckpt这个文件夹下有预训练的模型，可以直接运行得到实验结果。如果自己训练测试，weibo数据集比较小，过拟合问题比较严重，受参数初始化的影响，结果有可能会有一些波动，你可以多次实验看一下结果或者调整一下个别参数。

我做了一些小改动，在您的代码里，由于字到id的映射没有保存，所以训练和测试的时候都要运行一次预处理把数据变成id的形式，但是如果测试集和验证集的数据有一些对方不同的字，那么运行两次预处理，有些字对应的id就会变化，embedding感觉就不对应了，所以我在预处理里面就一次性处理了三个数据集，训练集，验证集，和测试集。在训练集中训练，在验证集中挑一个最好的模型，然后在测试集中得到最终效果。您说的个别参数是指哪些参数可能有影响呢？谢谢。

**Comment by CPF-NLPR** [comment]
我在训练和测试时进行预处理，这两次得到的字和id的对应关系是一样的。因为我只考虑了训练集和测试集中的字。关键的参数比如dropout，隐层单元数等等，都会有一定影响。

**Comment by goingcoder** [comment]
我看了一下预训练的embeddinng,有一万多个字，我在一个大型新闻语料里提取的字也就是五六千。看了一下代码，每次预处理都会先加载预训练的embeddings,word2id每次先在这里面提取，然后训练数据，测试数据提取，最后是分词数据提取。我觉得两次预处理一样的话，很可能是训练数据和测试数据和验证数据出现的字在embedding中全都出现过了。

**Comment by goingcoder** [comment]
我刚才也尝试重新下载了您的代码重新运行一下，发现报错了，我直接在测试集上测试，我们的字数是不同的，我在测试集，训练集，分词数据，embedding文件中提取的word2id数目是20770，加载模型的时候提示我是20779，Assign requires shapes of both tensors to match. lhs shape= [20770,100] rhs shape= [20779,100]，所以我觉得还是一次性处理完所有数据比较好。您第一次预处理应该出来的是训练集和验证集的数据，虽然您文件中写的测试集文件，我觉得这个地方需要换成验证集集文件的，然后训练完，在验证集上找一个最好的模型，第二次预处理是处理测试集文件，在测试集文件得到最好的效果。不过我觉得不太安全，总感觉验证集和测试集如果有一些对方没有的字，这个word2id在两次处理的时候，有些字不是同一个id了。这也是我考虑一次性处理三个文件的原因。谢谢。

**Comment by goingcoder** [comment]
如果直接按照您readme写的操作
训练的时候，使用这两行命令
```
python preprocess_weibo.py
python train_weibo.py
```
测试的时候，使用这两行
```
python preprocess_weibo.py
python test_weibo.py
```
里面什么都不修改的话，那就真的是过拟合了。

**Comment by CPF-NLPR** [comment]
weibo数据集比较小，必然会存在过拟合的问题，可以通过正则化的方法减少一些
