### ISSUE TITLE
最大长度80

### ISSUE THREAD

**Issue by goingcoder** [CPF-NLPR/AT4ChineseNER#12]
按照您设置的最大长度80，我对三个数据集进行统计，
训练集，验证集，测试集，句子总数为：135 270 270
大于80的句子数占各个数据集的比例为：0.22，0.20,0.22，跟您前面说过的小于80的占95%以上不符，也就是你说的这个比例是小于0.05，这个差距有点大，谢谢。

**Comment by CPF-NLPR** [comment]
在SighanNER数据集最大长度设为80可以覆盖绝大多数样本，在微博数据集比例较大一些。我们也尝试了在微博数据集上设置更大长度，效果基本上都差别不大
