### ISSUE TITLE
InvalidArgumentError with Other MSRA Dataset

### ISSUE THREAD

**Issue by mkrdip** [CPF-NLPR/AT4ChineseNER#13]
Hi there, 

As SIGHANNER dataset isn't available on your given link, if other MSRA datasets are used it shows following errors.

GPU:
```
InvalidArgumentError (see above for traceback): indices[0,1] = 59 is not in [0, 49)
	 [[node ner_model/ner_crf/GatherV2_1 (defined at <ipython-input-2-f9f661903dfb>:176) ]]
```

CPU: 

```
InvalidArgumentError (see above for traceback): indices[0,0] = 59 is not in [0, 49)
         [[Node: ner_model/ner_crf/Gather_1 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, 
validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"]
(ner_model/ner_crf/Reshape_3, ner_model/ner_crf/add_3)]]
```

**Comment by SABER-LOVE** [comment]
Hello，

I want to know wether the SighanNER dataset and MSRA NER dataset are the same dataset?

**Comment by CPF-NLPR** [comment]
> Hello，
> 
> I want to know wether the SighanNER dataset and MSRA NER dataset are the same dataset?

**Comment by CPF-NLPR** [comment]
Hi, @SABER-LOVE ,The SighanNER dataset and MSRA NER dataset are the same datasets.
