### ISSUE TITLE
how can you sent this paper to me?

### ISSUE THREAD

**Issue by HaimianYu** [CPF-NLPR/AT4ChineseNER#2]
1106929652@qq.com
thanks

**Comment by CPF-NLPR** [comment]
I will upload the paper

**Comment by HaimianYu** [comment]
I've been waiting for a long time and  I'm looking forward to your paper. thanks

**Comment by HaimianYu** [comment]
> I will upload the paper

I've been waiting for a long time and I'm looking forward to your paper. thanks

**Comment by CPF-NLPR** [comment]
I have updated the project, you can download the paper now.

**Comment by HaimianYu** [comment]
> I have updated the project, you can download the paper now.

Thank you very much
