### ISSUE TITLE
where can I get the paper?

### ISSUE THREAD

**Issue by BaiStone2017** [CPF-NLPR/AT4ChineseNER#4]
Excuse me .where can I get the paper? Or can you send the paper to my email?1302563090@qq.com 
thx

**Comment by zxteloiv** [comment]
As the readme stated, you can obtain a pdf file from ACL Anthology so far because the main conference of EMNLP 2018 was already ended.
The more detailed citing information is available at [HERE](https://aclanthology.coli.uni-saarland.de/papers/D18-1017/d18-1017)
