### ISSUE TITLE
could not find the SigHan dataset

### ISSUE THREAD

**Issue by max-yue** [CPF-NLPR/AT4ChineseNER#7]
Hi, dear PengFei Cao, I have try my best to get the SigHan Dataset, But still not find. I have send a email to you for help. So if you can, can you share the dataset with me?

**Comment by max-yue** [comment]
my email 17210240247@fudan.edu.cn

**Comment by CPF-NLPR** [comment]
I have sent it to your email.

**Comment by haowenke** [comment]
Could not find SigHan NER dataset either. Is it possible to send me a copy? my email address is haowke@gmail.com

**Comment by SABER-LOVE** [comment]
Hello， could you please give me the SigHan NER dataset?  I have try my best to find it, but i also can not find a true dataset. My email is wwk993032101@gmail.com
