### ISSUE TITLE
关于句子长度

### ISSUE THREAD

**Issue by goingcoder** [CPF-NLPR/AT4ChineseNER#8]
您好，您设定了num_steps =80,也就是对于句子长度大于80的部分会被裁剪，也就意味着测试集也会丢掉一部分数据，跟别人对比的时候，数据集也就是不同的，是这样吗？谢谢。

**Comment by CPF-NLPR** [comment]
我们做过相应的统计，句子长度设为80已经可以覆盖绝大多数的样本

**Comment by goingcoder** [comment]
> 我们做过相应的统计，句子长度设为80已经可以覆盖绝大多数的样本

请问这个比例大概多少呢？那测试集是不是跟别人有些不一样了呢？谢谢。

**Comment by CPF-NLPR** [comment]
超过95%，具体数值记不太清楚了。测试集和别人是一样的，只是超过80的部分会被截掉，性能基本上没有什么影响，只是训练的效率会提升
